
# ============================================
#  Project 19: Employee Information Form
#  Topics Used: print(), input()
# ============================================

print("=" * 55)
print("         EMPLOYEE INFORMATION FORM")
print("=" * 55)
print("  🏢 Python Tech Solutions Pvt. Ltd. 🏢")
print("  HR Department - New Employee Onboarding")
print("=" * 55)

print("\n--- PERSONAL DETAILS ---")
name = input("Enter employee full name: ")
dob = input("Enter date of birth (DD/MM/YYYY): ")
gender = input("Enter gender (Male/Female/Other): ")
phone = input("Enter phone number: ")
email = input("Enter personal email ID: ")
address = input("Enter residential address: ")
city = input("Enter city: ")
pan = input("Enter PAN card number: ")
aadhar = input("Enter Aadhar number (last 4 digits): ")

print("\n--- EMPLOYMENT DETAILS ---")
emp_id = input("Enter employee ID (given by HR): ")
designation = input("Enter designation/job title: ")
department = input("Enter department: ")
joining_date = input("Enter joining date (DD/MM/YYYY): ")
salary = input("Enter annual CTC (in LPA): ")
work_email = input("Enter work email ID: ")
reporting_manager = input("Enter reporting manager's name: ")
work_location = input("Enter work location (City/WFH/Hybrid): ")

print("\n--- EDUCATIONAL DETAILS ---")
highest_qual = input("Enter highest qualification: ")
specialization = input("Enter specialization: ")
university = input("Enter university/college name: ")
pass_year = input("Enter year of passing: ")

print()
print("=" * 55)
print("       🏢 EMPLOYEE ID CARD DETAILS 🏢")
print("=" * 55)
print(f"  Employee ID      : {emp_id}")
print(f"  Name             : {name}")
print(f"  Designation      : {designation}")
print(f"  Department       : {department}")
print(f"  Work Email       : {work_email}")
print(f"  Phone            : {phone}")
print(f"  {'─' * 50}")
print(f"  DOB              : {dob} | Gender: {gender}")
print(f"  Address          : {address}, {city}")
print(f"  PAN              : {pan}")
print(f"  Aadhar           : XXXX-XXXX-{aadhar}")
print(f"  {'─' * 50}")
print(f"  Joining Date     : {joining_date}")
print(f"  Annual CTC       : {salary} LPA")
print(f"  Reporting To     : {reporting_manager}")
print(f"  Work Location    : {work_location}")
print(f"  {'─' * 50}")
print(f"  Qualification    : {highest_qual} in {specialization}")
print(f"  University       : {university} ({pass_year})")
print("=" * 55)
print("  ✅ Employee Records Updated Successfully!")
print("  🎉 Welcome Aboard! Happy to have you with us!")
print("=" * 55)
