
# ============================================
#  Project 13: Event Registration Form
#  Topics Used: print(), input()
# ============================================

print("=" * 50)
print("       EVENT REGISTRATION FORM")
print("=" * 50)
print("  🎉 Welcome to the Event Registration Portal 🎉")
print("=" * 50)

print("\n--- EVENT DETAILS ---")
event_name = input("Enter event name: ")
event_date = input("Enter event date (DD/MM/YYYY): ")
event_venue = input("Enter event venue: ")

print("\n--- PARTICIPANT DETAILS ---")
part_name = input("Enter your full name: ")
age = input("Enter your age: ")
gender = input("Enter your gender (Male/Female/Other): ")
email = input("Enter your email: ")
phone = input("Enter your phone number: ")
college = input("Enter your college/organization name: ")
city = input("Enter your city: ")
t_shirt = input("Enter T-Shirt size (XS/S/M/L/XL/XXL): ")
veg = input("Are you Vegetarian? (Yes/No): ")
emergency_contact = input("Enter emergency contact number: ")

print()
print("=" * 50)
print("     🎊 REGISTRATION CONFIRMATION 🎊")
print("=" * 50)
print(f"  Event       : {event_name}")
print(f"  Date        : {event_date}")
print(f"  Venue       : {event_venue}")
print(f"  {'─' * 44}")
print(f"  Name        : {part_name}")
print(f"  Age/Gender  : {age} / {gender}")
print(f"  Email       : {email}")
print(f"  Phone       : {phone}")
print(f"  College/Org : {college}")
print(f"  City        : {city}")
print(f"  T-Shirt     : {t_shirt}")
print(f"  Food Pref   : {'Vegetarian' if veg.lower() == 'yes' else 'Non-Vegetarian'}")
print(f"  Emergency   : {emergency_contact}")
print("=" * 50)
print("  ✅ Registration Successful! See you at the event!")
print("=" * 50)
